
running 4 tests
test it_exits ... FAILED
test it_fails ... FAILED
test it_panics ... ok
test it_works ... ok

failures:

---- it_exits stdout ----
---- it_exits stderr ----
note: got unexpected return code 123
---- it_fails stdout ----
hello, world
testing123
---- it_fails stderr ----
testing321
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `5`', $DIR/test-panic-abort.rs:31:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    it_exits
    it_fails

test result: FAILED. 2 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

