
running 2 tests
test $DIR/failed-doctest-output.rs - OtherStruct (line 21) ... FAILED
test $DIR/failed-doctest-output.rs - SomeStruct (line 11) ... FAILED

failures:

---- $DIR/failed-doctest-output.rs - OtherStruct (line 21) stdout ----
error[E0425]: cannot find value `no` in this scope
  --> $DIR/failed-doctest-output.rs:22:1
   |
LL | no
   | ^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
Couldn't compile the test.
---- $DIR/failed-doctest-output.rs - SomeStruct (line 11) stdout ----
Test executable failed (exit code 101).

stdout:
stdout 1
stdout 2

stderr:
stderr 1
stderr 2
thread 'main' panicked at 'oh no', $DIR/failed-doctest-output.rs:7:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.



failures:
    $DIR/failed-doctest-output.rs - OtherStruct (line 21)
    $DIR/failed-doctest-output.rs - SomeStruct (line 11)

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

